### ISSUE TITLE
Telegraf hostname typos

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/srl-telemetry-lab#18]
https://github.com/srl-labs/srl-telemetry-lab/blob/02f0e3d2f16d251627818c8b92017bb2a7d10764/configs/telegraf/telegraf.conf#L2

Leaf3 is referenced twice, leaf2 not at all. Same for other lines below

**Comment by hellt** [comment]
ah, that is an old leftover, we don't use telegraf for this lab
I will remove this file
