### ISSUE TITLE
Grafana Security Vulnerability on port 3000/tcp

### ISSUE THREAD

**Issue by dwatt-nokia** [srl-labs/srl-telemetry-lab#33]
IT scans are detecting vulnerability severity 5 against "Grafana Anonymous Access Enabled" on port 3000/tcp.

Is there anything we can do about this - even post deployment configuration?

**Comment by hellt** [comment]
This was a deliberate choice. The lab is not exposed to the internet, hence anonymous access is granted.
You can change the configuration by disabling it.

**Comment by dwatt-nokia** [comment]
Thanks, unfortunately ‘not being exposed to the internet’ is no longer a valid excuse for us to use with IT scans.
I didn't want to break the telemetry set-up.
I can see that these system settings are defined in grafana.ini or custom.ini (or overridden in ENV variables) - sorry, not Grafana guru - I see SSH is disabled - how you you login to edit the config?

**Comment by dwatt-nokia** [comment]
also this will be over-ridden every time I (re)deploy - correct?

**Comment by dwatt-nokia** [comment]
Or could I add something to the JSON file?

[root@clab grafana]# pwd
/etc/containerlab/clab-srl-telemetry/configs/grafana
[root@clab grafana]# ls *
dashboards.yml  datasource.yml

dashboards:
telemetry-dashboard.json
