### ISSUE TITLE
Flowchart plugin is depreciated.

### ISSUE THREAD

**Issue by steve-nscale** [srl-labs/srl-telemetry-lab#43]
Apparently the flowchart plugin is depreciated, any plans to move this to Canvas instead?

**Comment by hellt** [comment]
With pleasure, but canvas can't achieve what we are doing here with drawio

**Comment by steve-nscale** [comment]
yeah i did wonder about that. Hmm.... im happy to help out where i can.

**Comment by hellt** [comment]
there is another plugin, which also works with diagrams.net (as opposed to canvas), but it is a bit freash. @FloSch62 knows its name, I keep forgetting it

**Comment by FloSch62** [comment]
The flow panel is kind of a successor, it also relies on drawio svgs

https://github.com/andymchugh/andrewbmchugh-flow-panel

**Comment by hellt** [comment]
we switched to the flow panel in #46
