### ISSUE TITLE
Lab fails to start

### ISSUE THREAD

**Issue by drosend** [srl-labs/srl-telemetry-lab#44]
Hey everyone,

When I attempt to start this lab I get the following errors:

ERRO[0029] failed to run postdeploy task for node leaf3: command execution error:Error: Error in path:
    [InvalidArgument] Unacceptable syslog configuration
Error 'Revert failed':
    [Internal] Failed to revert to pre-commit configuration

Inspecting the SR Linux containers show that they failed to get their startup config. I wasn't really able to debug past that point. Any pointers?

**Comment by hellt** [comment]
Hi

Change the image version to 24.7.2

**Comment by drosend** [comment]
Fixed it. Thanks a bunch!
